yml file (#47)
* testing

* tried husky, couldn't get it to work with nested fodlers. Will try github actions again

* commented out check-localhost file

* added a line of code to yml file, moved github workflow back to root folder

* deleted workflow files inside client directory

* testing url again

diff --git a/.github/workflows/check-url.yml b/.github/workflows/check-url.yml
--- a/.github/workflows/check-url.yml
+++ b/.github/workflows/check-url.yml
@@ -1,29 +1,27 @@
-# name: Check-URL
+name: Check-URL
 
-# on:
-#   push:
-#     branches:
-#       - main
-#   pull_request:
-#     branches:
-#       - main
+on:
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
 
-# jobs:
-#   check:
-#     runs-on: ubuntu-latest
+jobs:
+  check:
+    runs-on: ubuntu-latest
 
-#     steps:
-#       - name: Check URL
-#         uses: actions/checkout@v2
+    steps:
+      - name: Check URL
+        uses: actions/checkout@v2
 
-#       - name: Install dependencies
-#         run: npm install
-
-#       - name: Uncommented-Localhost-URL
-#         run: |
-#           if grep -q '// const URL = "http://localhost:3001"' client/src/URL.jsx; then
-#             echo "Success: Found commented localhost URL in your code."
-#             exit 0
-#           else
-#             exit 1
-#           fi
+      - name: Uncommented-Localhost-URL
+        run: |
+          if grep -q '// const URL = "http://localhost:3001"' client/src/URL.jsx; then
+            echo "Success: Found commented localhost URL in your code."
+            exit 0
+          else
+            echo "Error: Please comment out localhost URL."
+            exit 1
+          fi
